window.SITE_CONFIG = {
  recipientName: "Himanya",
  senderName: "From FAMILY",
  password: "2026",
  lockHint: "A tiny secret before the celebration ✦",
  year: "2026",
  heroMessage: "A little scrolling story filled with memories, wishes, cake and one more surprise.",
  song1: {
    src: "assets/audio/song1.mp3",
    title: "SONG",
    artist: "",
  },
  memories: [
    { src: "assets/photos/memory/mem-1.JPG", caption: "One of those moments we want to keep close." },
    { src: "assets/photos/memory/mem-2.JPG", caption: "A memory that still makes us smile." },
    { src: "assets/photos/memory/mem-3.JPG", caption: "A little moment, a lot of meaning." },
    { src: "assets/photos/memory/mem-4.JPG", caption: "The kind of day worth remembering." },
    { src: "assets/photos/memory/mem-5.JPG", caption: "Another chapter for the memory box." },
  ],
  cakeBefore: "cake cut cheyi himanya",
  cakeAfter: "tineyi inka screen lone",
  gallery: [
    { src: "assets/photos/gallery/himmu-1.JPG", caption: "A moment to keep." },
    { src: "assets/photos/gallery/himmu-2.JPG", caption: "One for the memory box." },
    { src: "assets/photos/gallery/himmu-3.JPG", caption: "A little piece of today." },
    { src: "assets/photos/gallery/himmu-4.JPG", caption: "A day we will remember." },
    { src: "assets/photos/gallery/himmu-5.JPG", caption: "One more happy frame." },
    { src: "assets/photos/gallery/himmu-6.JPG", caption: "Just because this felt special." },
  ],
  wishInstruction: "udhu candle",
  wishDone: "Your wish is off to the stars ✦",
  wishDoneSub: "May the year ahead give you many reasons to smile.",
  noteText: "Dear Himanya,\n\nToday is a small reminder that you are deeply loved, endlessly celebrated, and always worth cheering for.\n\nThere will be many more words later. For now, just keep this little note as a reminder: the people who made this are proud of you, happy for you, and wishing the very best for you.\n\nHappy birthday.\n\nWith love,",
  wishCards: [
    { text: "nuv korikunadi neraverali ani korukuntunamu" },
    { text: "nuv unatha stayi ki veltav ani namutunamu" },
    { text: "ni decisions nuv tesukoni strong ga munduki sagutavu ani korukuntunamu" },
    { text: "nidra lo mo kalu tho tanavu ani korukuntunamu" },
    { text: "Vamsi ni devudu la bavistav ani korukuntunamu" },
    { text: "family ni proud feel chese la nuv anukunadi sadistav ani Nammutunamu" },
  ],
  surpriseVideoUrl: "https://drive.google.com/file/d/1si6u7APX23AqRFRyPnPoaQoXK5vNYVVe/view?usp=drivesdk",
};
